import type { Metadata } from 'next'
import Link from 'next/link'
import { generateMetadata as genMeta } from '@/lib/seo'
import BreadcrumbNav from '@/components/seo/BreadcrumbNav'

export const metadata: Metadata = genMeta({
  title: 'Terms of Service — Mentneo',
  description: 'Read Mentneo\'s Terms of Service. Usage policies, acceptable use, API terms, enterprise agreements, and intellectual property rights.',
  path: '/terms',
  keywords: ['terms of service', 'terms and conditions', 'API terms', 'acceptable use policy', 'Mentneo legal'],
})

const sections = [
  { title: '1. Acceptance of Terms', content: 'By accessing or using Mentneo\'s services, APIs, or website, you agree to be bound by these Terms of Service. If you are using Mentneo on behalf of an organization, you represent that you have authority to bind that organization. If you do not agree to these terms, do not use the service.' },
  { title: '2. Permitted Use', content: 'You may use Mentneo\'s services for lawful purposes in accordance with these terms. You may integrate our APIs into your products and services, subject to our usage limits and the restrictions in Section 3.' },
  { title: '3. Prohibited Activities', content: 'You may not use Mentneo\'s services to: generate illegal content, harassment, hate speech, or content that incites violence; impersonate others or create deceptive content; circumvent our safety systems or content policies; attempt to extract training data or reverse-engineer our models; resell API access without authorization; or violate any applicable law or regulation.' },
  { title: '4. API Usage & Limits', content: 'API usage is subject to rate limits specified on our pricing page. We reserve the right to throttle or suspend accounts that abuse the service or violate these terms. Exceeding free tier limits will require upgrading to a paid plan.' },
  { title: '5. Intellectual Property', content: 'You retain ownership of content you provide as input. Mentneo retains ownership of all models, software, and systems. Outputs generated by our models may be used by you for any purpose permitted by law, subject to our content policy. You may not use outputs to train competing AI models without explicit written permission.' },
  { title: '6. Privacy & Data', content: 'Our collection and use of your data is governed by our Privacy Policy. Enterprise customers may negotiate additional data processing terms. We do not sell personal data.' },
  { title: '7. Service Availability', content: 'We target 99.9% uptime for API services (99.99% for enterprise contracts). We may perform scheduled maintenance with advance notice. We are not liable for downtime beyond the remedies specified in your SLA.' },
  { title: '8. Limitation of Liability', content: 'To the maximum extent permitted by law, Mentneo\'s total liability to you shall not exceed the amount you paid in the 12 months preceding the claim. We are not liable for indirect, incidental, or consequential damages.' },
  { title: '9. Changes to Terms', content: 'We may update these terms with 30 days notice via email or service notification. Continued use after the effective date constitutes acceptance. Enterprise contracts have separate change processes defined in the contract.' },
  { title: '10. Governing Law', content: 'These terms are governed by the laws of India. Disputes shall be resolved through binding arbitration in Hyderabad, India, except where arbitration is prohibited by applicable law.' },
]

export default function TermsPage() {
  return (
    <main id="main-content" style={{ background: '#050505', minHeight: '100vh' }}>
      <div className="container-xl" style={{ padding: 'clamp(6rem, 10vw, 9rem) 0 4rem', maxWidth: '780px', margin: '0 auto' }}>
        <BreadcrumbNav items={[{ name: 'Terms of Service', url: '/terms' }]} />
        <h1 style={{ fontSize: 'clamp(1.75rem, 4vw, 2.5rem)', fontWeight: 700, letterSpacing: '-0.03em', color: '#fff', marginBottom: '0.5rem' }}>Terms of Service</h1>
        <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.875rem', marginBottom: '3rem' }}>Last updated: July 1, 2026</p>

        <p style={{ color: 'rgba(255,255,255,0.55)', lineHeight: 1.8, marginBottom: '2rem', fontSize: '0.95rem' }}>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of Mentneo&apos;s services, APIs, software, and website. Please read them carefully.
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          {sections.map(s => (
            <div key={s.title}>
              <h2 style={{ fontSize: '1.05rem', fontWeight: 700, color: '#fff', marginBottom: '0.5rem' }}>{s.title}</h2>
              <p style={{ color: 'rgba(255,255,255,0.5)', lineHeight: 1.8, fontSize: '0.9rem' }}>{s.content}</p>
            </div>
          ))}
        </div>

        <div style={{ marginTop: '3rem', paddingTop: '2rem', borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
          <Link href="/privacy" style={{ color: '#60a5fa', textDecoration: 'none', fontSize: '0.875rem' }}>Privacy Policy</Link>
          <Link href="/security" style={{ color: '#60a5fa', textDecoration: 'none', fontSize: '0.875rem' }}>Security</Link>
          <Link href="/contact" style={{ color: '#60a5fa', textDecoration: 'none', fontSize: '0.875rem' }}>Contact Legal</Link>
        </div>
      </div>
    </main>
  )
}
